name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.3.2
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  dio: ^5.1.2
  flutter_local_notifications: ^14.1.0
  rxdart: ^0.27.5

  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  package_info_plus: ^4.0.1
  open_filex: ^4.2.2
  sensors_plus: ^3.0.1
  share_plus: ^7.0.1
  chopper: ^6.1.2
  url_launcher: ^6.1.6

dev_dependencies:
  lint: ^2.1.2
